### ISSUE TITLE
Needs update after breaking changes to chroma layers in ComfyUI.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [ClownsharkBatwing/RES4LYF#206]
ComfyUI has added a feature that breaks your samplers, probably this: https://github.com/comfyanonymous/ComfyUI/commit/f60923590c3f2fd05e166e2ec57968aaf7007dd0

```
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2131, in load_custom_node
    module_spec.loader.exec_module(module)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\RES4LYF\__init__.py", line 6, in <module>
    from . import conditioning
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\RES4LYF\conditioning.py", line 24, in <module>
    from .beta.constants import MAX_STEPS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\RES4LYF\beta\__init__.py", line 2, in <module>
    from . import rk_sampler_beta
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\RES4LYF\beta\rk_sampler_beta.py", line 20, in <module>
    from .rk_guide_func_beta    import LatentGuide
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\RES4LYF\beta\rk_guide_func_beta.py", line 24, in <module>
    from ..models import PRED
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\RES4LYF\models.py", line 47, in <module>
    from comfy.ldm.chroma.layers import SingleStreamBlock as ChromaSingleStreamBlock, DoubleStreamBlock as ChromaDoubleStreamBlock
ImportError: cannot import name 'SingleStreamBlock' from 'comfy.ldm.chroma.layers' (D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\chroma\layers.py)

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\RES4LYF module for custom nodes: cannot import name 'SingleStreamBlock' from 'comfy.ldm.chroma.layers' (D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\chroma\layers.py)
```

**Comment by gifandy** [comment]
yes, you need now to import from comfy.ldm.flux.layers. in line 47
see https://github.com/comfyanonymous/ComfyUI/pull/10746

**Comment by GalaxyTimeMachine** [comment]
Replace with this line and it works (tested) :)

`from comfy.ldm.flux.layers import SingleStreamBlock as ChromaSingleStreamBlock, DoubleStreamBlock as ChromaDoubleStreamBlock`

**Comment by shonlg** [comment]
碰到了同样的问题，补充完整一点解决方法：
找到：ComfyUI/custom_nodes/RES4LYF/models.py 文件，备份后打开：
找到：from comfy.ldm.chroma.layers import SingleStreamBlock as ChromaSingleStreamBlock, DoubleStreamBlock as ChromaDoubleStreamBlock
大约在47行，
替换为：from comfy.ldm.flux.layers import SingleStreamBlock as ChromaSingleStreamBlock, DoubleStreamBlock as ChromaDoubleStreamBlock

重新启动就能正常启动了。

**Comment by kpu3uc** [comment]
already fixed in the new comfyui update

**Comment by GalaxyTimeMachine** [comment]
Is not fixed, the change allows the nodes to load, but functionality is broken if it tries to use it.
